### Yarp health check
GET {{baseyarpurl}}/health
Accept: application/json

### Yarp proxy to API
GET {{baseyarpurl}}
redirect-allowed: true

### Yarp proxy to API without header
GET {{baseyarpurl}}
    
### Yarp proxy to get envs values
GET {{baseyarpurl}}/envs