### GET Health Check
GET {{baseapiurl}}/health
Accept: application/json

### get call from root
GET {{baseapiurl}}/
Accept: application/text

### GET status
GET {{baseapiurl}}/status

### GET status with pause
GET {{baseapiurl}}/pause/5
Accept: application/json