apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-requests-cpu
  namespace: alt
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: apidemo
  minReplicas: 1
  maxReplicas: 50
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70